apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-frontend
  template:
    metadata:
      labels:
        app: management-frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: management-frontend
        image:docker.io/gunjanust/management-frontend:8bfbf14a2edcd11c531f53a85d5803a190a4800c
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
