apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management-service
  template:
    metadata:
      labels:
        app: student-management-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: student-management-service
        image:docker.io/gunjanust/management-backend:ef03fe79d47485cd9b10ff967b97e8129a2f1802
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: JWT_SECRET
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
