apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-frontend
  template:
    metadata:
      labels:
        app: management-frontend
    spec:
      containers:
      - name: management-frontend
        image:docker.io/gunjan1603/management-frontend:7be67ceac6652b761c4cf4503cf41e7eeb4963c5
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
